openapi: 3.0.1
info:
  title: Final-Project-B-6
  description: API Pemesanan Ticketing Pesawat
  version: 1.0.0
servers:
  - url: http://localhost:3000/api/v1
tags:
  - name: "Users"
    description: Operations about user
paths:
  /auth/register:
    post:
      tags:
        - "Auth"
      summary: Register user
      description: Register user with the provided information.
      requestBody:
        $ref: "#/components/requestBodies/createUser"

      responses:
        201:
          description: User created was successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: User Created Successfully
                  data:
                    $ref: "#/components/schemas/UserResponse"

        400:
          description: Input must be required!
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Input must be required
                  data:
                    example: ~

        401:
          description: Email already used!
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Email already used!
                  data:
                    example: ~

  /auth/login:
    post:
      tags:
        - "Auth"
      summary: Login user
      description: Login user with the provided information.
      requestBody:
        $ref: "#/components/requestBodies/createLogin"

      responses:
        201:
          description: Login was successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Login was successfull
                  data:
                    $ref: "#/components/schemas/LoginResponse"

        400:
          description: invalid email or password!
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: invalid email or password!
                  data:
                    example: ~

  /auth/authenticate:
    get:
      tags:
        - "Auth"
      summary: Authenticate user
      description: Authenticate user with the token.

      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: OK
                  data:
                    $ref: "#/components/schemas/UserResponse"

        403:
          description: Token not provided!
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: token not provided!!
                  data:
                    example: ~

        409:
          description: jwt malformed!
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: jwt malformed
                  data:
                    example: ~
      security:
        - bearerAuth: []

  /users:
    get:
      tags:
        - "Users"
      summary: Get all users
      parameters:
        - schema:
            type: string
          name: search
          in: query
          description: search for get first_name users
      description: Get all users
      responses:
        200:
          description: Success get all users
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Success
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        first_name:
                          type: string
                          example: Bagus Dwi
                        last_name:
                          type: string
                          example: Putra Adiyono
                        email:
                          type: string
                          example: sugab.dwi88@gmail.com

  /forget-pass:
    post:
      tags:
        - "Users"
      summary: Forget Password Email User
      description: Forget Password Email User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: sugab.dwi88@gmail.com

      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Success Send Email Forget Password"

        404:
          description: user not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "user not found"
                  data:
                    example: ~

  /reset-pass:
    post:
      tags:
        - "Users"
      summary: Reset Password Email User
      parameters:
        - schema:
            type: string
          name: token
          in: query
          description: token for update password
      description: Reset Password Email User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                  example: qwerty
                passwordConfirmation:
                  type: string
                  example: qwerty

      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Your password has been updated successfully!"
                  data:
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: Bagus Dwi
                      email:
                        type: string
                        example: sugab.dwi88@gmail.com

        400:
          description: Both password and password confirmation are required!!
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Both password and password confirmation are required!!"
                  data:
                    example: ~

        401:
          description: Please ensure that the password and password confirmation match!
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Please ensure that the password and password confirmation match!"
                  data:
                    example: ~

        403:
          description: Invalid or expired token!
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Invalid or expired token!"
                  data:
                    example: ~
  /schedule:
    post:
      description: Find ticket
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                from:
                  type: string
                  example: jakarta
                destination:
                  type: string
                  example: melbourne
                date_departure:
                  type: string
                  example: 20/06/2024
                date_return:
                  type: string
                  example: 20/06/2024
                # total_passenger:
                #   type: integer
                # example: 2
                seat_class:
                  type: integer
                  example: 2
                passenger:
                  type: object
                  properties:
                    adult:
                      type: integer
                      example: 1
                    children:
                      type: integer
                      example: 1
      responses:
        "200":
          description: Succes
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                    example: success retrive data
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        plane:
                          type: string
                          example: jetAir
                        arive_at:
                          type: string
                          example: 07:00
                        leave_at:
                          type: string
                          example: 07:30
                        from:
                          type: string
                          example: jakarta
                        destination:
                          type: string
                          example: melbourne
                        estimation:
                          type: string
                          example: "7.30"
                        seat_class:
                          type: array
                          items:
                            properties:
                              class:
                                type: string
                                example: ekonomi
                              price:
                                type: string
                                example: 100000
    get:
      parameters:
        - name: query
          in: query
          required: false
          description: Query parameter to filter content
          schema:
            type: string
      responses:
        "200":
          description: Succes
          content:
            application/json:
              schema:
                type: object
  /class:
    get:
      responses:
        "200":
          description: Succes
          content:
            application/json:
              schema:
                type: object
  /city:
    get:
      responses:
        "200":
          description: Succes
          content:
            application/json:
              schema:
                type: object

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    UserResponse:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Bagus Dwi
        email:
          type: string
          example: sugab.dwi88@gmail.com
    LoginResponse:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Bagus Dwi
        email:
          type: string
          example: sugab.dwi88@gmail.com
        token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RfbmFtZSI6IkJhZ3VzIER3aSIsImxhc3RfbmFtZSI6IlB1dHJhIEFkaXlvbm8iLCJlbWFpbCI6InN1Z2FiLmR3aTg4QGdtYWlsLmNvbSIsImlhdCI6MTcxNDY1NTQ1N30.7mHMjtq0QvKWfZ41Nb5XMXKyfkcg4l7LX34yC-HBj3A

  requestBodies:
    createLogin:
      content:
        application/json:
          schema:
            type: object
            properties:
              email:
                type: string
                example: sugab.dwi88@gmail.com
              password:
                type: string
                example: 123456
    createUser:
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
                example: Bagus Dwi
              email:
                type: string
                example: sugab.dwi88@gmail.com
              password:
                type: string
                example: 123456
