name: Deploy to Railway Production ENV

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Packages
        run: npm install

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Install Prisma
        run: npm i prisma

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Run Migrations
        run: |
          export DATABASE_URL="${{ secrets.PROD_DATABASE_URL }}"
          npx prisma migrate deploy

      - name: Run Seeder
        run: |
          export DATABASE_URL="${{ secrets.PROD_DATABASE_URL }}"
          npx prisma db seed

      - name: Deploy to Railway
        run: railway up --service ${{ secrets.PROD_RAILWAY_SERVICE_ID }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_PROD_TOKEN }}
